// INITIALIZATION
export const APP_LOAD_SUCCESS = 'APP_LOAD_SUCCESS'
export const APP_LOAD_ERROR = 'APP_LOAD_ERROR'

// STATISTICS
export const STATISTICS_REQUESTED = 'STATISTICS_REQUESTED'
export const STATISTICS_RECEIVED = 'STATISTICS_RECEIVED'
export const STATISTICS_ERRORED = 'STATISTICS_ERRORED'

// FILTER
export const START_DATE_UPDATED = 'START_DATE_UPDATED'
export const END_DATE_UPDATED = 'END_DATE_UPDATED'
export const INTERVAL_UPDATED = 'INTERVAL_UPDATED'
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED'
export const FAVORITE_VIEWS_UPDATED = 'FAVORITE_VIEWS_UPDATED'
export const TOP_FAVORITES_UPDATED = 'TOP_FAVORITES_UPDATED'
