// INITIALIZATION
export const APP_LOAD_SUCCESS = 'APP_LOAD_SUCCESS'
export const APP_LOAD_ERROR = 'APP_LOAD_ERROR'

// STATISTICS
export const USAGE_DATA_REQUESTED = 'USAGE_DATA_REQUESTED'
export const USAGE_DATA_RECEIVED = 'USAGE_DATA_RECEIVED'
export const USAGE_DATA_ERRORED = 'USAGE_DATA_ERRORED'

// FILTER
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED'
export const START_DATE_UPDATED = 'START_DATE_UPDATED'
export const END_DATE_UPDATED = 'END_DATE_UPDATED'
export const INTERVAL_UPDATED = 'INTERVAL_UPDATED'
export const AGGREGATION_LEVEL_UPDATED = 'AGGREGATION_LEVEL_UPDATED'
export const CHART_TYPE_UPDATED = 'CHART_TYPE_UPDATED'
export const EVENT_TYPE_UPDATED = 'EVENT_TYPE_UPDATED'
export const PAGE_SIZE_UPDATED = 'PAGE_SIZE_UPDATED'
export const SORT_ORDER_UPDATED = 'SORT_ORDER_UPDATED'
